version: "3.9"

services:
  nats:
    image: nats:2.10
    container_name: nats
    ports:
      - "4222:4222" # client connection
      - "6222:6222" # clustering
      - "8222:8222" # monitoring UI
    command:
      - "-js" # enable JetStream
      - "-sd" # enable storage
      - "/data/jetstream" # storage path
      - "-m"
      - "8222"
    volumes:
      - ./docker/nats-server.conf:/etc/nats/nats-server.conf
      - ./docker/nats-data:/data/jetstream

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-changeme}

volumes:
  redis_data:
